# Generated by Django 4.2.7 on 2023-12-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('content', models.CharField(max_length=555, verbose_name='содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='превью')),
                ('date_cr', models.DateField(blank=True, null=True, verbose_name='дата создания')),
                ('publication_sign', models.BooleanField(default=True)),
                ('views_counter', models.IntegerField(verbose_name='количество просмотров')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
