# Generated by Django 4.2.7 on 2023-12-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views_counter',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество просмотров'),
        ),
    ]
