# Generated by Django 4.2.7 on 2023-12-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_slug_alter_blog_views_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publication_sign',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views_counter',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
