# Generated by Django 4.2.6 on 2023-10-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='будет отменено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_ch',
            field=models.DateField(blank=True, null=True, verbose_name='дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_cr',
            field=models.DateField(blank=True, null=True, verbose_name='дата создания'),
        ),
    ]
